name: InfiniteParkour
version: '${project.version}'
main: mfw.when.infiniteparkour.InfiniteParkour
api-version: 1.18
authors: [ wekj ]
softdepend:
  - VoidGen
description: Infinite Parkour Yay
commands:
  infiniteparkour:
    description: Starts the parkour hopefully
    aliases:
      - parkour
  test:
  reset:
  tpparkour:
  leaveparkour:
    description: Leaves your current parkour session. Only for operators
    aliases: lvpk
